version: "3.9"
services:
  db:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'covid'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './db-prod:/var/lib/mysql'
      - './local:/var/lib/mysql-files'

  app:
    build: app/
    ports:
      - "5000:5000"
    restart: always

    
