apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-prod
  labels:
    app: app-prod
spec:
  selector:
    matchLabels:
      app: app-prod
  template:
    metadata:
      labels:
        app: "app-prod"
    spec:
      nodeSelector:
        disktype: ssd
      containers:
        - name: "app-prod"
          image: "rpaprojectfiap/rpa_project_app"
          ports:
          - containerPort: 8080
          